name: Node.js CI/CD Workflow

on:
  push:
    branches: [ main ] # 监听 main 分支 push 事件

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.0.0] # 指定 Node.js 版本
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 使用 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # registry-url: https://npm.pkg.github.com/
          # scope: '@loxehate' 

      - name: 安装依赖
        run: |
          cd build
          npm install -g pnpm
          pnpm install

      - name: 打包生成 npm 包
        run: |
          tar -zcvf node.tar.gz ./build

      - name: 生成 GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.sha }}
          tag_name: ${{ github.sha }}
          files: |
            ./node.tar.gz